export const customer = [
  {
    id: 9,
    customer: 11908,
    customer_profile: {
      id: 11908,
      name: "Ram",
      color: [182, 73, 99],
      email: "jesus_christ@church.com",
      pincode: "Mumbai",
      location_name: "Mumbai, Maharashtra, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },

  {
    id: 10,
    customer: 11909,
    customer_profile: {
      id: 11909,
      name: "Aryan Patel",
      color: [54, 162, 235],
      email: "aryan.patel@example.com",
      pincode: "400001",
      location_name: "Mumbai, Maharashtra, India",
      type: "C",
      profile_pic: null,
      gst: "27AABCU9603R1ZM",
    },
  },
  {
    id: 11,
    customer: 11910,
    customer_profile: {
      id: 11910,
      name: "Sanjana Rao",
      color: [75, 192, 192],
      email: "sanjana.rao@example.com",
      pincode: "600001",
      location_name: "Chennai, Tamil Nadu, India",
      type: "C",
      profile_pic: null,
      gst: "33AAACW1234E1Z4",
    },
  },
  {
    id: 12,
    customer: 11911,
    customer_profile: {
      id: 11911,
      name: "Rohan Mehta",
      color: [153, 102, 255],
      email: "rohan.mehta@example.com",
      pincode: "560001",
      location_name: "Bengaluru, Karnataka, India",
      type: "C",
      profile_pic: null,
      gst: "29AABCT2468N1Z6",
    },
  },
  {
    id: 13,
    customer: 11912,
    customer_profile: {
      id: 11912,
      name: "Priya Sharma",
      color: [255, 159, 64],
      email: "priya.sharma@example.com",
      pincode: "500001",
      location_name: "Hyderabad, Telangana, India",
      type: "C",
      profile_pic: null,
      gst: "36AAACG9371G1Z5",
    },
  },
  {
    id: 14,
    customer: 11913,
    customer_profile: {
      id: 11913,
      name: "Karan Verma",
      color: [255, 99, 132],
      email: "karan.verma@example.com",
      pincode: "411001",
      location_name: "Pune, Maharashtra, India",
      type: "C",
      profile_pic: null,
      gst: "27AAACM3333A1Z7",
    },
  },
  {
    id: 15,
    customer: 11914,
    customer_profile: {
      id: 11914,
      name: "Neha Gupta",
      color: [255, 206, 86],
      email: "neha.gupta@example.com",
      pincode: "110001",
      location_name: "New Delhi, Delhi, India",
      type: "C",
      profile_pic: null,
      gst: "07AABCU9604R1ZM",
    },
  },
  {
    id: 16,
    customer: 11915,
    customer_profile: {
      id: 11915,
      name: "Amit Singh",
      color: [54, 162, 235],
      email: "amit.singh@example.com",
      pincode: "700001",
      location_name: "Kolkata, West Bengal, India",
      type: "C",
      profile_pic: null,
      gst: "19AABCT2469N1Z6",
    },
  },
  {
    id: 17,
    customer: 11916,
    customer_profile: {
      id: 11916,
      name: "Anjali Das",
      color: [75, 192, 192],
      email: "anjali.das@example.com",
      pincode: "380001",
      location_name: "Ahmedabad, Gujarat, India",
      type: "C",
      profile_pic: null,
      gst: "24AAACG9372G1Z5",
    },
  },
  {
    id: 18,
    customer: 11917,
    customer_profile: {
      id: 11917,
      name: "Vikram Nair",
      color: [153, 102, 255],
      email: "vikram.nair@example.com",
      pincode: "302001",
      location_name: "Jaipur, Rajasthan, India",
      type: "C",
      profile_pic: null,
      gst: "08AAACW1235E1Z4",
    },
  },
  {
    id: 19,
    customer: 11918,
    customer_profile: {
      id: 11918,
      name: "Meera Iyer",
      color: [255, 159, 64],
      email: "meera.iyer@example.com",
      pincode: "462001",
      location_name: "Bhopal, Madhya Pradesh, India",
      type: "C",
      profile_pic: null,
      gst: "23AABCT2470N1Z6",
    },
  },
];
