export const mockProductData = [
  {
    id: 209,
    display_id: 8,
    owner: 1079,
    name: "New Product",
    category: "The god of War",
    characteristics: "New Product Characteristics",
    features: "",
    brand: "New Product Brand",
    skus: [
      {
        id: 248,
        selling_price: 54,
        max_retail_price: 44,
        amount: 33,
        unit: "kg",
        quantity_in_inventory: 0,
        product: 209,
      },
      {
        id: 247,
        selling_price: 32,
        max_retail_price: 32,
        amount: 33,
        unit: "kg",
        quantity_in_inventory: 0,
        product: 209,
      },
      {
        id: 246,
        selling_price: 23,
        max_retail_price: 21,
        amount: 22,
        unit: "kg",
        quantity_in_inventory: 1,
        product: 209,
      },
    ],
    updated_on: "2024-05-24T12:46:41.995873Z",
    adding_date: "2024-05-24T12:46:41.995828Z",
  },
  {
    id: 210,
    name: "Another Product",
    category: "The goddess of Love",
    skus: [
      {
        id: 250,
        selling_price: 40,
        max_retail_price: 35,
        amount: 30,
        unit: "kg",
        quantity_in_inventory: 5,
      },
      {
        id: 251,
        selling_price: 28,
        max_retail_price: 26,
        amount: 25,
        unit: "kg",
        quantity_in_inventory: 2,
      },
    ],
  },

  {
    id: 211,
    name: "Product A",
    category: "Category A",
    skus: [
      {
        id: 252,
        selling_price: 20,
        max_retail_price: 18,
        amount: 15,
        unit: "kg",
        quantity_in_inventory: 3,
      },
      {
        id: 253,
        selling_price: 15,
        max_retail_price: 12,
        amount: 10,
        unit: "kg",
        quantity_in_inventory: 7,
      },
    ],
  },
  {
    id: 212,
    name: "Product B",
    category: "Category B",
    skus: [
      {
        id: 254,
        selling_price: 25,
        max_retail_price: 22,
        amount: 20,
        unit: "kg",
        quantity_in_inventory: 4,
      },
      {
        id: 255,
        selling_price: 18,
        max_retail_price: 16,
        amount: 17,
        unit: "kg",
        quantity_in_inventory: 6,
      },
    ],
  },
  {
    id: 213,
    name: "Product C",
    category: "Category C",
    skus: [
      {
        id: 256,
        selling_price: 30,
        max_retail_price: 28,
        amount: 25,
        unit: "kg",
        quantity_in_inventory: 2,
      },
      {
        id: 257,
        selling_price: 22,
        max_retail_price: 20,
        amount: 18,
        unit: "kg",
        quantity_in_inventory: 8,
      },
    ],
  },
  {
    id: 214,
    name: "Product D",
    category: "Category D",
    skus: [
      {
        id: 258,
        selling_price: 35,
        max_retail_price: 32,
        amount: 30,
        unit: "kg",
        quantity_in_inventory: 5,
      },
      {
        id: 259,
        selling_price: 28,
        max_retail_price: 25,
        amount: 24,
        unit: "kg",
        quantity_in_inventory: 5,
      },
    ],
  },
  {
    id: 215,
    name: "Product E",
    category: "Category E",
    skus: [
      {
        id: 260,
        selling_price: 40,
        max_retail_price: 38,
        amount: 35,
        unit: "kg",
        quantity_in_inventory: 3,
      },
      {
        id: 261,
        selling_price: 30,
        max_retail_price: 28,
        amount: 26,
        unit: "kg",
        quantity_in_inventory: 7,
      },
    ],
  },
  {
    id: 216,
    name: "Product F",
    category: "Category F",
    skus: [
      {
        id: 262,
        selling_price: 45,
        max_retail_price: 42,
        amount: 40,
        unit: "kg",
        quantity_in_inventory: 2,
      },
      {
        id: 263,
        selling_price: 35,
        max_retail_price: 32,
        amount: 30,
        unit: "kg",
        quantity_in_inventory: 8,
      },
    ],
  },
  {
    id: 217,
    name: "Product G",
    category: "Category G",
    skus: [
      {
        id: 264,
        selling_price: 50,
        max_retail_price: 48,
        amount: 45,
        unit: "kg",
        quantity_in_inventory: 4,
      },
      {
        id: 265,
        selling_price: 40,
        max_retail_price: 38,
        amount: 36,
        unit: "kg",
        quantity_in_inventory: 6,
      },
    ],
  },
  {
    id: 218,
    name: "Product H",
    category: "Category H",
    skus: [
      {
        id: 266,
        selling_price: 55,
        max_retail_price: 52,
        amount: 50,
        unit: "kg",
        quantity_in_inventory: 1,
      },
      {
        id: 267,
        selling_price: 45,
        max_retail_price: 42,
        amount: 40,
        unit: "kg",
        quantity_in_inventory: 9,
      },
    ],
  },
];
